build(gh pages): disable npm caching because of an unexpected error
Error: .github/workflows/pages.yml (Line: 19, Col: 16):
2
Error: The template is not valid. .github/workflows/pages.yml (Line: 19, Col: 16): hashFiles('**/package-lock.json') couldn't finish within 120 seconds.